### ISSUE TITLE
Add "Deploy to Heroku" button

### ISSUE THREAD

**Issue by veloxy** [veloxy/purl#2]
Add a [Deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button) button to the readme so people can set it up without hassle or knowledge of programming.

I had [already started](https://github.com/veloxy/purl/commits/heroku-deploy) on it but I'm not that familiar with Heroku and kind of gave up on it very early. I'd still like to have it added so I'm adding it for hacktoberfest for people that would like to give it a go.

Note: This requires some additional configuration for a production env and parameters.yml need to be setup somehow. Symfony experience is likely required.

**Comment by yuriy-yarosh** [comment]
Sign me in.

**Comment by amitsin6h** [comment]
@veloxy bro you need to verify your app.json with heroku or if I verify app.json with my heroku account it will get deploy in my heroku account instead of yours. All you need is to verify your app.json and once your done let me know I will add button for you.

**Comment by amitsin6h** [comment]
@veloxy Its good that your app.json is  in root directory. Just verify your app.json with heroku and let me know i will add the "deploy on heroku" button

**Comment by amitsin6h** [comment]
@veloxy let me check it also has a alternative way to check app.json

**Comment by veloxy** [comment]
@amitsin6h Sorry, maybe I should have been more specific but it's more than just adding the button. It also requires some configuration for a production environment and things like the [parameters.yml](https://github.com/veloxy/purl/blob/master/app/config/parameters.yml.dist) need to be setup somehow.

**Comment by yuriy-yarosh** [comment]
@veloxy yup, the most common way is to pass 'em via command prompt, and it's the most recommended one. Thus your _docker-compose_ _mysql_ credentials should be pulled from there too.

**Comment by yuriy-yarosh** [comment]
@veloxy Actually, it's a good idea to add some [packer.io](https://packer.io) recipes for AWS and DO too.

**Comment by veloxy** [comment]
@yuriy-yarosh That could be a good idea, I'm more a DO fan myself. 😄
