### ISSUE TITLE
Move css into its own file

### ISSUE THREAD

**Issue by veloxy** [veloxy/purl#3]
Move the [css](https://github.com/veloxy/purl/blob/master/src/AppBundle/Resources/views/layout.html.twig#L8-L60) into a separate file, optionally add a gulpfile and convert the css to less/sass.

**Comment by amitsin6h** [comment]
@veloxy I have moved css to new file

**Comment by amitsin6h** [comment]
@veloxy Now am also trying to convert css to less and sass with gulp. I will submit once i get success

**Comment by REPTILEHAUS** [comment]
Id be happy to give this a shot if you are still looking for a hand ?

**Comment by veloxy** [comment]
@REPTILEHAUS Sure, go ahead!
